server:
  port: 8085
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch_zhangjicheng
      cluster-nodes: 127.0.0.1:9300
    rabbitmq:
      host: 127.0.0.1
      username: guest
      password: guest
      virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10